input {
  file {
	path => "/var/log/hp2/adbhoney/adbhoney/adbhoney.json"
      sincedb_path => "/dev/null"
start_position => beginning
	codec => json
	type => "adbhoneyhp2"
  }
}
filter {
  if [src_ip] {
	mutate {
  	  add_field => { "src_ip_rdns" => "%{src_ip}" }
	}
	dns {
  	  reverse => [ "src_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "src_ip"
    	  target => "geoip"
  	}
  }


  if [dest_ip] {
	mutate {
  	  add_field => { "dest_ip_rdns" => "%{dest_ip}" }
	}
	dns {
  	  reverse => [ "dest_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "dest_ip"
    	  target => "geoip"
  	}
  }
}
output {
  if [type] == "adbhoneyhp2" {
	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
  	  index => "adbhoney-honeypot2-%{+YYYY-MM-dd}"
	}
  }
}
