input {
  file {
	path => "/var/log/hp1/cowrie/cowrie/cowrie.json"
      sincedb_path => "/dev/null"
	start_position => beginning
	codec => json
	type => "cowriehp1"
  }
}
filter {
  date {
match => ["timestamp", "ISO8601"]
target => "@timestamp"
timezone => "Europe/Madrid"
  }
}
output {
  if [type] == "cowriehp1" {
	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
  	  index => "cowrie-honeypot1-%{+YYYY-MM-dd}"
	}
  }
}
