input {
  udp {
	port => 2055
	codec => netflow
	type => "fprobe"
  }
}
filter {
  if [type] == "fprobe" {
	if [fprobe][protocol] == 1 {
  	  mutate {
    	    add_field => { "protocol_name" => "ICMP" }
  	  }
	}
	else if [fprobe][protocol] == 2 {
  	  mutate {
    	    add_field => { "protocol_name" => "IGMP" }
  	  }
	}
	else if [fprobe][protocol] == 6 {
  	  mutate {
    	    add_field => { "protocol_name" => "TCP" }
  	  }
	}
	else if [fprobe][protocol] == 17 {
  	  mutate {
    	    add_field => { "protocol_name" => "UDP" }
  	  }
	}
	else if [fprobe][protocol] == 27 {
  	  mutate {
    	    add_field => { "protocol_name" => "RDP" }
  	  }
	}
	else if [fprobe][protocol] == 3 {
  	  mutate {
    	    add_field => { "protocol_name" => "TCP-SSL" }
  	  }
	}
	else if [fprobe][protocol] == 11 {
  	  mutate {
    	    add_field => { "protocol_name" => "FTP" }
  	  }
	}
   }
}
output {
  if [type] == "fprobe" {
	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
  	  index => "fprobe-%{+YYYY-MM-dd}"
	}
  }
}
