input {
  jdbc {
jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.10.jar"
jdbc_driver_class   => "org.postgresql.Driver"
jdbc_connection_string => "jdbc:postgresql://172.16.0.101:5432/mailoney"
jdbc_user           => "${DB_USER}"
jdbc_password       => "${DB_PASS}"


statement => "SELECT * FROM smtp_sessions WHERE id > :sql_last_value ORDER BY id ASC;"


use_column_value    => true
tracking_column     => "id"
tracking_column_type => "numeric"
last_run_metadata_path => "/var/lib/logstash/.mailoney_smtp_sessions_last_id"


schedule            => "* * * * *"
jdbc_default_timezone => "UTC"
  }
}
filter {
  mutate {
	add_field => { type => "mailoneyhp2-sessions" }
rename => {
  "ip_address" => "src_ip"
        "dest_ip" => "dst_ip"
        "port" => "src_port"
        "dest_port" => "dst_port"
    }
  }
  if [src_ip] {
	mutate {
  	  add_field => { "src_ip_rdns" => "%{src_ip}" }
	}
	dns {
  	  reverse => [ "src_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "src_ip"
    	  target => "src_geoip"
  	}
  }


  if [dst_ip] {
	mutate {
  	  add_field => { "dst_ip_rdns" => "%{dst_ip}" }
	}
	dns {
  	  reverse => [ "dst_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "dst_ip"
    	  target => "dst_geoip"
  	}
  }
}
output {
  if [type] == "mailoneyhp2-sessions" {
	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
  	  index => "mailoney-honeypot2-sessions-%{+YYYY-MM-dd}"
	}
  }
}
