input {
  jdbc {
jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.7.10.jar"
jdbc_driver_class   => "org.postgresql.Driver"
jdbc_connection_string => "jdbc:postgresql://172.16.0.101:5432/mailoney"
jdbc_user           => "${DB_USER}"
jdbc_password       => "${DB_PASS}"


statement => "
  SELECT
  c.id,
  c.timestamp,
  c.session_id,
  c.auth_string,
  s.ip_address   AS src_ip,
  s.port         AS src_port,
  s.dest_ip      AS dst_ip,
  s.dest_port    AS dst_port,
  s.server_name  AS honeypot_server
  FROM credentials c
  JOIN smtp_sessions s ON c.session_id = s.id
  WHERE c.id > :sql_last_value
  ORDER BY c.id ASC;"
use_column_value    => true
tracking_column     => "id"
tracking_column_type => "numeric"
last_run_metadata_path => "/var/lib/logstash/.mailoney_smtp_credentials_last_id"
schedule            => "* * * * *"
jdbc_default_timezone => "UTC"
type => "mailoneyhp2-credentials"
  }
 }
filter {
  if [src_ip] {
	mutate {
  	  add_field => { "src_ip_rdns" => "%{src_ip}" }
	}
	dns {
  	  reverse => [ "src_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "src_ip"
    	  target => "src_geoip"
  	}
  }
  if [dst_ip] {
	mutate {
  	  add_field => { "dst_ip_rdns" => "%{dst_ip}" }
	}
	dns {
  	  reverse => [ "dst_ip_rdns" ]
  	  action => "replace"
	}
  	geoip {
    	  source => "dst_ip"
    	  target => "dst_geoip"
  	}
  }
  if [auth_string] =~ /^[A-Za-z0-9+\/=]{8,}$/ {
ruby {
  code => 'begin
         decoded = Base64.decode64(event.get("auth_string"))
         parts = decoded.split("\x00").reject(&:empty?)
         if parts.length >= 2
           event.set("smtp_auth_user", parts[0])
           event.set("smtp_auth_password", parts[1])
         end
         event.set("smtp_auth_decoded", decoded.gsub("\x00", " | "))
        rescue => e
          event.set("smtp_auth_decode_error", e.message)
        end'
    }
  }
}
output {
  if [type] == "mailoneyhp2-credentials" {
	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
  	  index => "mailoney-honeypot2-credentials-%{+YYYY-MM-dd}"
	}
  }
}
