input {
  file {
	path => "/var/log/hp2/miniprint/miniprint/miniprint.log"
      sincedb_path => "/dev/null"
	start_position => beginning
	type => "miniprinthp2"
  }
}
filter {
  if [type] == "miniprinthp2" {
grok { 
  match => { "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+-\s+%{LOGLEVEL:log_level}\s+-\s+%{WORD:method}\s+-\s+%{WORD:operation}\s+-\s+%{GREEDYDATA:log_message}"
  }
}
  date {
    match => [ "timestamp", "ISO8601", "yyyy-MM-dd'T'HH:mm:ss.SSSSSSZZZZZ" ]
    target => "@timestamp"
    timezone => "UTC"
    remove_field => [ "timestamp" ]
  }
  if [method] == "handle" and [operation] == "open_conn" {
    grok {
      match => { "log_message" => "%{IP:client_ip}" }
    }
    mutate {
      add_field => { "connection_event" => "open"
                     "handler_type"     => "connection" }
    }
      geoip {
          source => "client_ip"
          target => "geoip"
      }
  }
  else if [method] == "handle" and [operation] == "close_conn" {
    grok {
      match => { "log_message" => "%{IP:client_ip}" }
    }
    mutate {
      add_field => { "connection_event" => "close"
                     "handler_type"     => "connection" }
    }
  }
  else if [method] == "handle" and [operation] == "request"
          and [log_message] =~ /FSDIRLIST/ {
    grok {
      match => {
        "log_message" => "b'@PJL FSDIRLIST NAME=\"%{DATA:pjl_fs_path}\"\s+ENTRY=%{NUMBER:pjl_entry}\s+COUNT=%{NUMBER:pjl_count}"
      }
    }
    mutate {
      add_field => { "handler_type" => "filesystem"
                     "pjl_command"  => "FSDIRLIST" }
    }
  }
  else if [method] == "fsdirlist" and [operation] == "request" {
    grok {
      match => {
        "log_message" => "Requested dir:\s+'%{DATA:fs_requested_path}'"
      }
    }
    mutate {
      add_field => { "handler_type" => "filesystem" }
    }
  }
  else if [method] == "fsdirlist" and [operation] == "response" {
    grok {
      match => {
        "log_message" => "b'@PJL FSDIRLIST NAME=\"%{DATA:pjl_fs_path}\"\s+ENTRY=%{NUMBER:pjl_entry}"
      }
    }
    mutate {
      add_field => { "handler_type" => "filesystem"
                     "pjl_command"  => "FSDIRLIST" }
    }
  }
  else if [method] == "echo" and [operation] == "request" {
    mutate {
      add_field => { "handler_type" => "echo" }
      add_tag   => ["echo_request"]
    }
  }
 
  else if [method] == "echo" and [operation] == "response" {
    grok {
      match => {
        "log_message" => "Responding with:\s+b'@PJL ECHO DELIMITER%{NUMBER:echo_delimiter_id}"
      }
    }
    mutate {
      add_field => { "handler_type" => "echo"
                     "pjl_command"  => "ECHO" }
    }
  }
  else if [method] == "handle" and [operation] == "response" {
    mutate {
      add_field => { "handler_type" => "connection" }
    }
 
    if [log_message] =~ /FSDIRLIST/ {
      grok {
        match => {
          "log_message" => "FSDIRLIST NAME=\"%{DATA:pjl_fs_path}\""
        }
      }
      mutate {
        add_field => { "pjl_command" => "FSDIRLIST" }
      }
    }
 
    if [log_message] =~ /ECHO DELIMITER/ {
      grok {
        match => {
          "log_message" => "ECHO DELIMITER%{NUMBER:echo_delimiter_id}"
        }
      }
    }
  }


  }
}
output {
  if [type] == "miniprinthp2" {
	if "_grokparsefailure" not in [tags] {
  	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
    	  index => "miniprint-honeypot2-%{+YYYY-MM-dd}"
  	}
    }
  }
}
