input {
  file {
	path => "/var/log/hp1/wordpress/wordpress/access.log"
      sincedb_path => "/dev/null"
	start_position => beginning
	type => "wordpresshp1"
  }
}
filter {
  if [type] == "wordpresshp1" {
  	grok {
    	  match => { "message" => "%{IP:client_ip} %{DATA:ident} %{DATA:auth} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATH:request_path}(?:%{URIPARAM:request_query})? HTTP/%{NUMBER:http_version}\" %{NUMBER:response_code:int} %{NUMBER:bytes:int} \"(?:%{URI:referrer}|-)\" \"%{DATA:user_agent}\"" }
  	}
  	geoip {
    	  source => "client_ip"
    	  target => "geoip"
  	}
	date {
  	  match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
	}
  }
}
output {
  if [type] == "wordpresshp1" {
	if "_grokparsefailure" not in [tags] {
  	elasticsearch {
        ssl_certificate_authorities => "/etc/logstash/http_ca.crt"
        user => "${ES_USER}"
        password => "${ES_PASS}"
  	  hosts => ["https://localhost:9200"]
    	  index => "wordpress-honeypot1-%{+YYYY-MM-dd}"
  	}
    }
  }
}
